version: '3.6'

services:

# Used by Keycloak and GraphQL
    db:
        env_file: .env

        container_name: q_db
        image: postgres

        volumes:
            - ./initdb/:/docker-entrypoint-initdb.d/

# Expose the database port so database admin tools can connect, like VSCODE 
        ports:
            - '5432:5432'

        restart: always



# GraphQL interface for the database
    gql:
        env_file: 
            - .env
            - initkc/private_data/token.env

        image: hasura/graphql-engine:v2.1.0-beta.3
        container_name: q_gql
        
        links: 
            - db

        ports:
            - '8092:8080'

        command:
            - graphql-engine
            - serve

        restart: always

        
# Keycloak auth
    auth:
        env_file: .env

        container_name: q_auth
        image: openremote/keycloak

        # mount configuration files
        volumes:
            - ./initkc:/docker-entrypoint-initdb.d/
            - ./initkc/kctheme:/opt/jboss/keycloak/themes/qiksar

        links: 
            - db

        ports:
            - 8093:8080

        restart: always
    
    qiktrak:
        env_file: .env
        
        container_name: qiktrak
        image: namsource/qiktrak:latest

        volumes:
            - ./qiktrak:/qiktrak

        links:
            - db
            - gql

        command:
            - node
            - qik-trak-cli.js

    #app:
    #    env_file: .env
    #    container_name: q_app
    #    image: node:latest


# nginx proxy
    proxy:
        env_file: .env
        
        container_name: q_proxy
        image: nginx
        
        volumes:
          - ./initnginx/nginx.conf:/etc/nginx/nginx.conf
          - ./initnginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
          - ./initnginx/private_data/ssl:/etc/nginx/ssl
          - ./app_root:/usr/share/nginx/app_root
        
        ports:
            - 80:80
            - 443:443

        links:
            - gql
            - auth
